import {ApiError,PREFIX,body,database,digest,limit,nonce,origin,readCookie,result,secureCookie,settings,variables,type DB} from '../../../admin/core';
import {verifyInvite} from '../../../account/auth-security';
import {authConfig} from '../../../account/auth-config';
const providers:Record<string,{authorize:string;token:string;user:string;scope:string}>={
 github:{authorize:'https://github.com/login/oauth/authorize',token:'https://github.com/login/oauth/access_token',user:'https://api.github.com/user',scope:'read:user'},
 google:{authorize:'https://accounts.google.com/o/oauth2/v2/auth',token:'https://oauth2.googleapis.com/token',user:'https://openidconnect.googleapis.com/v1/userinfo',scope:'openid profile'},
 linuxdo:{authorize:'https://connect.linux.do/oauth2/authorize',token:'https://connect.linux.do/oauth2/token',user:'https://connect.linux.do/api/user',scope:''}
};
type Context={params:Promise<{provider:string;action:string}>};
export const dynamic='force-dynamic';
export async function POST(r:Request,c:Context){return handle(r,c)}
export async function GET(r:Request,c:Context){return handle(r,c)}
async function handle(r:Request,c:Context){let db:DB|undefined;try{const {provider:id,action}=await c.params,p=providers[id];if(!p||!['start','callback'].includes(action))throw new ApiError('登录方式不可用',404);db=await database();const s=await settings(db),config=s.sso[id];if(!config?.enabled||!config.clientId||!config.clientSecret)throw new ApiError('该登录方式尚未启用',403);const site=variables().SITE_URL?new URL(variables().SITE_URL).origin:new URL(r.url).origin;if(site!==new URL(r.url).origin)throw new ApiError('Site origin mismatch',403);const callback=new URL('/api/sso/'+id+'/callback',site).href;
 if(action==='start'){if(r.method!=='POST')throw new ApiError('请从登录窗口发起第三方登录',405);origin(r);await limit(db,r,'sso-start',30);const b=await body(r,2000);const state=nonce(),browser=nonce(),verifier=nonce();await db.set(PREFIX+'oauth:'+digest(state),JSON.stringify({provider:id,browser:digest(browser),verifier,invite:String(b.inviteCode||'').slice(0,100),callback}),{EX:600});const url=new URL(p.authorize);url.search=new URLSearchParams({client_id:config.clientId,redirect_uri:callback,response_type:'code',state,...(p.scope?{scope:p.scope}:{}),...(id==='github'||id==='google'?{code_challenge:Buffer.from(digest(verifier),'hex').toString('base64url'),code_challenge_method:'S256'}:{})}).toString();return result({url:url.href},200,{'Set-Cookie':secureCookie(r,'resonance_oauth',browser,600)})}
 if(r.method!=='GET')throw new ApiError('请求方式不正确',405);await limit(db,r,'sso-callback',30);const url=new URL(r.url),state=url.searchParams.get('state')||'',code=url.searchParams.get('code')||'';if(!/^[a-f0-9]{64}$/.test(state)||!code||code.length>4096)throw new ApiError('授权未完成，请重新登录');const saved=await db.eval("local v=redis.call('GET',KEYS[1]);redis.call('DEL',KEYS[1]);return v",{keys:[PREFIX+'oauth:'+digest(state)],arguments:[]}) as string|null;if(!saved)throw new ApiError('授权已过期或已使用',403);const flow=JSON.parse(saved);if(flow.provider!==id||flow.callback!==callback||flow.browser!==digest(readCookie(r,'resonance_oauth')))throw new ApiError('授权来源校验失败',403);
 const tokenResponse=await fetch(p.token,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/x-www-form-urlencoded','User-Agent':'ResonanceMusic'},body:new URLSearchParams({grant_type:'authorization_code',client_id:config.clientId,client_secret:config.clientSecret,code,redirect_uri:callback,...(id==='github'||id==='google'?{code_verifier:flow.verifier}:{})}),redirect:'manual',signal:AbortSignal.timeout(12000)});if(!tokenResponse.ok)throw new ApiError('平台授权失败，请重新登录');const token=await tokenResponse.json() as {access_token?:string};if(!token.access_token)throw new ApiError('平台没有返回有效授权');const ur=await fetch(p.user,{headers:{Authorization:'Bearer '+token.access_token,Accept:'application/json','User-Agent':'ResonanceMusic'},redirect:'manual',signal:AbortSignal.timeout(12000)});if(!ur.ok)throw new ApiError('无法读取平台身份');const profile=await ur.json() as Record<string,unknown>;const subject=id==='google'?profile.sub:profile.id;if((typeof subject!=='string'&&typeof subject!=='number')||String(subject).length>200)throw new ApiError('平台身份无效');if(id==='linuxdo'&&profile.active===false)throw new ApiError('平台账号不可用',403);const identity=PREFIX+'sso:'+id+':'+digest(String(subject));let uid=await db.get(identity);if(!uid){verifyInvite((await authConfig()).inviteCode,flow.invite);const candidate=nonce().slice(0,32),username='sso_'+id+'_'+digest(String(subject)).slice(0,16),user={username,name:String(profile.name||profile.login||profile.username||username).slice(0,40),sso:{provider:id,subject:String(subject)},createdAt:Date.now(),lastLogin:Date.now()};uid=await db.eval("local old=redis.call('GET',KEYS[1]);if old then return old end if redis.call('EXISTS',KEYS[3])==1 then return '' end redis.call('SET',KEYS[1],ARGV[1]);redis.call('SET',KEYS[2],ARGV[2]);redis.call('SET',KEYS[3],ARGV[1]);return ARGV[1]",{keys:[identity,PREFIX+'user:'+candidate,PREFIX+'username:'+username],arguments:[candidate,JSON.stringify(user)]}) as string|null;if(!uid)throw new ApiError('账号建立失败，请联系管理员')}
 const user=JSON.parse(await db.get(PREFIX+'user:'+uid)||'null');if(!user||user.disabled)throw new ApiError('该用户已停用',403);await db.eval("local v=redis.call('GET',KEYS[1]);if not v then return 0 end local u=cjson.decode(v);u.lastLogin=tonumber(ARGV[1]);redis.call('SET',KEYS[1],cjson.encode(u));return 1",{keys:[PREFIX+'user:'+uid],arguments:[String(Date.now())]});const prior=readCookie(r,'resonance_session');if(/^[a-f0-9]{64}$/.test(prior))await db.del(PREFIX+'session:'+digest(prior));const session=nonce(),sessionKey=PREFIX+'session:'+digest(session);await db.set(sessionKey,uid,{EX:2592000});await db.set(sessionKey+':issued',String(Date.now()),{EX:2592000});return new Response(null,{status:303,headers:{Location:'/', 'Cache-Control':'no-store','Set-Cookie':secureCookie(r,'resonance_session',session,2592000)}});
 }catch(e){return result({error:e instanceof ApiError?e.message:e instanceof Error&&e.name==='AuthSecurityError'?e.message:'第三方登录暂时失败，请返回网站重试'},e instanceof ApiError?e.status:400)}finally{db?.destroy()}}
