import {sceneCategories,moodCategories,genreCategories,type CuratedFeed,type CuratedPlaylist} from '../../curated-types';
import type {Mix,Song} from '../../music-types';
const categories=[...new Set([...sceneCategories,...moodCategories,...genreCategories])];
let cache:CuratedFeed|undefined,pending:Promise<CuratedFeed>|undefined;const details=new Map<string,{until:number;mix:Mix}>();
async function json(path:string){const r=await fetch('https://music.163.com'+path,{signal:AbortSignal.timeout(10000),redirect:'manual'});if(!r.ok)throw Error('歌单暂时无法读取');return r.json() as Promise<any>}
function cover(raw:unknown){try{const u=new URL(String(raw).replace(/^http:/,'https:'));if(!/^p\d+\.music\.126\.net$/.test(u.hostname))return '';u.search='';return u.href+'?param=600y600'}catch{return ''}}
async function list(category:string,order='hot'){const j=await json('/api/playlist/list?'+new URLSearchParams({cat:category,order,limit:'8',offset:'0'}));if(!Array.isArray(j.playlists))throw Error('列表暂不可用');return j.playlists.map((p:any):CuratedPlaylist=>({id:String(p.id),title:String(p.name),cover:cover(p.coverImgUrl),count:Number(p.trackCount)||0,plays:Number(p.playCount)||0,updated:Number(p.trackUpdateTime||p.updateTime||p.createTime)||0,category}))}
async function refresh(){const groups:Record<string,CuratedPlaylist[]>={};const tasks=[...categories];await Promise.all(Array.from({length:4},async()=>{while(tasks.length){const cat=tasks.shift()!;try{groups[cat]=await list(cat)}catch{groups[cat]=cache?.groups[cat]||[]}}}));const newest=[...new Map(Object.values(groups).flat().map(p=>[p.id,p])).values()].filter(p=>p.updated>0).sort((a,b)=>b.updated-a.updated).slice(0,8);if(!Object.values(groups).some(a=>a.length))throw Error('精选歌单暂不可用');return {groups,newest,updated:Date.now()}}
export async function GET(request:Request){try{const id=new URL(request.url).searchParams.get('id');if(id){if(!/^\d{1,18}$/.test(id))return Response.json({error:'歌单编号无效'},{status:400});const hit=details.get(id);if(hit&&hit.until>Date.now())return Response.json(hit.mix);const j=await json('/api/v6/playlist/detail?'+new URLSearchParams({id,n:'500',s:'0'}));const p=j.playlist;if(!p)throw Error('此歌单已失效或不可访问');let tracks=p.tracks||[];const ids=(p.trackIds||[]).slice(0,500).map((t:any)=>t.id);if(ids.length>tracks.length){const collected:any[]=[];for(let i=0;i<ids.length;i+=200){const d=await json('/api/song/detail?ids='+encodeURIComponent(JSON.stringify(ids.slice(i,i+200))));collected.push(...(d.songs||[]))}const map=new Map(collected.map(t=>[t.id,t]));tracks=ids.map((id:number)=>map.get(id)).filter(Boolean)}const songs:Song[]=tracks.map((s:any)=>{const ms=Number(s.dt||s.duration)||0;return {id:'wy_'+s.id,provider:'at38',title:s.name,artist:(s.ar||s.artists||[]).map((a:any)=>a.name).join(' / '),album:(s.al||s.album)?.name||'',cover:cover((s.al||s.album)?.picUrl),durationMs:ms,duration:ms?Math.floor(ms/60000)+':'+String(Math.floor(ms/1000)%60).padStart(2,'0'):''}});const mix:Mix={id,title:p.name,cover:cover(p.coverImgUrl),description:String(p.description||'').slice(0,240)+(p.trackCount>songs.length?` · 当前读取 ${songs.length} / ${p.trackCount} 首`:''),songs,tone:'green',updated:p.updateTime||Date.now()};if(details.size>=60)details.delete(details.keys().next().value!);details.set(id,{until:Date.now()+300000,mix});return Response.json(mix)}if(!cache||Date.now()-cache.updated>900000){pending??=refresh().then(d=>cache=d).finally(()=>{pending=undefined});await pending}return Response.json(cache,{headers:{'Cache-Control':'private, max-age=60'}})}catch{return cache&&!new URL(request.url).searchParams.has('id')?Response.json({...cache,stale:true}):Response.json({error:'精选歌单暂时无法加载，请稍后重试'},{status:503})}}

