'use client';
import {SsoButtons} from './site-features';
import {TurnstileChallenge} from './turnstile-challenge';
import {createContext,useContext,useEffect,useRef,useState} from 'react';
import {Plus} from 'lucide-react';

import {updateSearches} from './search-history';
import type {Song} from './music-types';
type Library={searches:string[];favorites:Song[];recent:Song[];playlists:{id:string;name:string;songs:Song[]}[]};const empty=():Library=>({searches:[],favorites:[],recent:[],playlists:[]});
export const AccountContext=createContext<(s:Song)=>void>(()=>{});
export function AddToPlaylist({song}:{song:Song}){const add=useContext(AccountContext);return <button className="icon-btn add-to-playlist" title="加入歌单" aria-label="加入歌单" onClick={()=>add(song)}><Plus size={24} strokeWidth={2}/></button>}
export function useAccount(){const [user,setUser]=useState<{id:string;name:string;username:string}|null>(null),[library,setLibrary]=useState<Library>(empty),[ready,setReady]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[adding,setAdding]=useState<Song|null>(null),[busy,setBusy]=useState(false);const identity=useRef<string|null>(null),chain=useRef(Promise.resolve());
 function guest():Library{try{return {...empty(),searches:updateSearches(JSON.parse(localStorage.getItem('resonance-searches-v1')||'[]'),'search-remove'),favorites:JSON.parse(localStorage.getItem('resonance-favorites-v2')||'[]'),recent:JSON.parse(localStorage.getItem('resonance-recent-v2')||'[]')}}catch{return empty()}}
 async function request(body?:unknown){const r=await fetch('/api/account',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const d=await r.json() as {error?:string;user:{id:string;name:string;username:string}|null;library:Library};if(!r.ok)throw Error(d.error);return d}
 useEffect(()=>{let live=true;request().then(d=>{if(live){identity.current=d.user?.id||null;setUser(d.user);setLibrary(d.library||guest())}}).catch(()=>{if(live){setLibrary(guest());setError('云端暂时无法连接，正在使用游客记录')}}).finally(()=>{if(live)setReady(true)});return()=>{live=false}},[]);
 function mutate(body:Record<string,unknown>){const owner=identity.current;if(!owner){setOpen(true);return}chain.current=chain.current.catch(()=>{}).then(async()=>{if(identity.current!==owner)return;try{const d=await request(body);if(identity.current===owner)setLibrary(d.library)}catch(e){if(identity.current===owner)setError((e as Error).message)}})}
 function local(update:(d:Library)=>Library){setLibrary(d=>{const next=update(d);try{localStorage.setItem('resonance-searches-v1',JSON.stringify(next.searches));localStorage.setItem('resonance-favorites-v2',JSON.stringify(next.favorites));localStorage.setItem('resonance-recent-v2',JSON.stringify(next.recent))}catch{}return next})}
 function searchHistory(action:'search-save'|'search-remove'|'search-clear',query?:string){if(!ready)return;if(identity.current)mutate({action,query});else local(d=>({...d,searches:updateSearches(d.searches,action,query)}))}
 function like(song:Song){if(!ready)return;const saved=!library.favorites.some(s=>s.id===song.id&&s.provider===song.provider);if(identity.current)mutate({action:'favorite',song,saved});else local(d=>({...d,favorites:saved?[song,...d.favorites]:d.favorites.filter(s=>s.id!==song.id||s.provider!==song.provider)}))}
 function record(song:Song){if(!ready)return;if(identity.current)mutate({action:'history',song});else local(d=>({...d,recent:[song,...d.recent.filter(s=>s.id!==song.id||s.provider!==song.provider)].slice(0,200)}))}
 async function authenticate(body:unknown){setBusy(true);setError('');try{await chain.current;const d=await request(body);identity.current=d.user?.id||null;setUser(d.user);setLibrary(d.library||guest());setOpen(false);setAdding(null)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function saveImport(body:Record<string,unknown>){const owner=identity.current;const task=chain.current.catch(()=>{}).then(async()=>{if(!owner||identity.current!==owner)throw Error('账号已变更，请重新导入');const d=await request(body);if(identity.current===owner)setLibrary(d.library)});chain.current=task.catch(()=>{});return task}
 return {saveImport,user,library,ready,error,setError,open,setOpen,adding,setAdding,busy,authenticate,mutate,like,record,searchHistory};}
export type Account=ReturnType<typeof useAccount>;
export function AccountDialog({account:a}:{account:Account}){const [register,setRegister]=useState(false),[captchaToken,setCaptchaToken]=useState(''),[captchaAttempt,setCaptchaAttempt]=useState(0);const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(a.open||a.adding)dialog.current?.showModal();else dialog.current?.close()},[a.open,a.adding]);return <dialog className="account-dialog" ref={dialog} onCancel={()=>{a.setOpen(false);a.setAdding(null)}}><button className="account-close" aria-label="关闭" onClick={()=>{a.setOpen(false);a.setAdding(null)}}>×</button>{a.adding&&a.user?<><h2>加入歌单</h2><p>{a.adding.title}</p>{a.library.playlists.map(p=><button className="account-choice" key={p.id} onClick={()=>{a.mutate({action:'add',id:p.id,song:a.adding});a.setAdding(null)}}>{p.name} · {p.songs.length} 首</button>)}{!a.library.playlists.length&&<p>请先到「我的歌单」创建歌单。</p>}</>:a.user?<><h2>{a.user.name}</h2><p>@{a.user.username} · 云端记录已启用</p><button className="primary-btn" disabled={a.busy} onClick={()=>a.authenticate({action:'logout'})}>退出登录</button></>:<><h2>{register?'创建音乐账号':'欢迎回到共鸣'}</h2><p>收藏、歌单与聆听记录，随账号一起保存。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);a.authenticate({action:register?'register':'login',username:f.get('username'),password:f.get('password'),name:f.get('name'),inviteCode:f.get('inviteCode'),turnstileToken:captchaToken}).finally(()=>{setCaptchaToken('');setCaptchaAttempt(v=>v+1)})}}>{register&&<label>昵称<input name="name" maxLength={40} autoComplete="nickname"/></label>}<label>账号<input required name="username" pattern="[a-zA-Z0-9_]{3,32}" placeholder="3–32 位字母、数字或下划线" autoComplete="username"/></label><label>密码<input required type="password" name="password" minLength={10} maxLength={128} placeholder="至少 10 位" autoComplete={register?'new-password':'current-password'}/></label><>{register&&<label>邀请码<input name="inviteCode" required maxLength={100} autoComplete="off" placeholder="请输入邀请码"/></label>}{a.open&&<TurnstileChallenge key={`${register}:${captchaAttempt}`} action={register?'register':'login'} onToken={setCaptchaToken}/>}</><button className="primary-btn" disabled={a.busy||!a.ready||!captchaToken}>{a.busy?'请稍候…':register?'注册并登录':'登录'}</button></form><button className="account-choice" onClick={()=>{setCaptchaToken('');setRegister(!register);a.setError('')}}>{register?'已有账号？去登录':'还没有账号？创建账号'}</button>{a.open&&<SsoButtons/>}</>}{a.error&&<p role="alert">{a.error}</p>}</dialog>}
export {PersonalPlaylists} from './personal-playlists';


