'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,Users,Settings,LogOut,Download,Upload,Search,KeyRound,Bell} from 'lucide-react';
import './admin.css';
type User={id:string;username:string;name:string;disabled:boolean;createdAt:number|null;lastLogin:number|null;sso:boolean};
const names:Record<string,string>={nodeseek:'NodeSeek',linuxdo:'Linux DO',github:'GitHub',google:'Google'};
export function AdminPanel({path}:{path:string}){
 const [authenticated,setAuthenticated]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[users,setUsers]=useState<User[]>([]),[cursor,setCursor]=useState('0'),[config,setConfig]=useState<any>(null),[logs,setLogs]=useState<{time:number;action:string}[]>([]),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[tab,setTab]=useState('users'),[base,setBase]=useState('');
 async function request(payload?:unknown,next='0'){const r=await fetch('/api/admin'+(!payload?'?cursor='+next:''),{method:payload?'POST':'GET',headers:{'Content-Type':'application/json','X-Admin-Path':path},...(payload?{body:JSON.stringify(payload)}:{})});const j=await r.json() as any;if(!r.ok){if(r.status===401)setAuthenticated(false);throw Error(j.error||'操作失败')}return j}
 async function load(next='0'){try{const j=await request(undefined,next);setAuthenticated(true);setUsers(prev=>next==='0'?j.users:[...new Map([...prev,...j.users].map((u:User)=>[u.id,u])).values()]);setCursor(j.cursor);setConfig(j.settings);setLogs(j.logs)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{setBase(location.origin);void load()},[]);
 async function act(payload:unknown,message:string){setBusy(true);setError('');setNotice('');try{const j=await request(payload);setNotice(message);return j}catch(e){setError((e as Error).message);return null}finally{setBusy(false)}}
 const visible=users.filter(u=>(status==='all'||(status==='disabled')===u.disabled)&&(u.username+' '+u.name).toLowerCase().includes(query.toLowerCase()));
 const update=(group:string,key:string,value:unknown)=>setConfig((c:any)=>({...c,[group]:{...c[group],[key]:value}}));
 const provider=(id:string,key:string,value:unknown)=>setConfig((c:any)=>({...c,sso:{...c.sso,[id]:{...c.sso[id],[key]:value}}}));
 async function save(){const j=await act({action:'settings',settings:config},'配置已保存');if(j)setConfig(j.settings)}
 if(loading)return <main className="admin-app admin-login"><ShieldCheck/><p>正在连接管理后台…</p></main>;
 if(!authenticated)return <main className="admin-app admin-login"><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const j=await act({action:'login',username:f.get('username'),password:f.get('password')},'');if(j){setError('');await load()}}}><ShieldCheck size={42}/><h1>共鸣 · 管理后台</h1><p>使用部署环境中配置的管理员账号登录</p><label>管理员名称<input name="username" autoComplete="username" required/></label><label>密码<input name="password" type="password" autoComplete="current-password" required minLength={16}/></label><button className="admin-primary" disabled={busy}>{busy?'正在验证…':'安全登录'}</button>{error&&<p role="alert" className="admin-error">{error==='请登录管理后台'?'':error}</p>}<a href="/">返回音乐网站</a></form></main>;
 return <div className="admin-app"><header className="admin-header"><div className="admin-brand"><ShieldCheck/><span><b>共鸣管理后台</b><small>用户 · 配置 · 数据</small></span></div><nav>{[['users','用户管理'],['settings','系统设置'],['data','数据管理']].map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav><button disabled={busy} onClick={async()=>{if(await act({action:'logout'},''))setAuthenticated(false)}}><LogOut size={16}/>退出</button></header><main className="admin-content">{error&&<p role="alert" className="admin-error">{error}</p>}{notice&&<p role="status" className="admin-notice">{notice}</p>}<div className="admin-stats">{[[Users,'已加载用户',users.length],[ShieldCheck,'正常用户',users.filter(u=>!u.disabled).length],[KeyRound,'启用 SSO',Object.values(config?.sso||{}).filter((p:any)=>p.enabled).length],[Bell,'网站公告',config?.announcement.enabled?'已启用':'未启用']].map(([Icon,label,value],i)=>{const I=Icon as typeof Users;return <article key={i}><I/><div><small>{String(label)}</small><b>{String(value)}</b></div></article>})}</div>
 {tab==='users'&&<div className="admin-columns"><section className="admin-card"><h2><Users/>用户列表</h2><p>查询当前已加载用户。旧账号缺少的时间信息显示为「—」。</p><div className="admin-toolbar"><label className="admin-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索用户名或昵称"/></label><select aria-label="用户状态" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部状态</option><option value="active">正常</option><option value="disabled">已停用</option></select><button disabled={busy} onClick={()=>void load()}>刷新</button></div><div className="admin-table-wrap"><table><thead><tr><th>用户</th><th>登录方式</th><th>状态</th><th>注册时间</th><th>最近登录</th><th>操作</th></tr></thead><tbody>{visible.map(u=><tr key={u.id}><td><b>{u.name}</b><small>@{u.username}</small></td><td>{u.sso?'第三方 SSO':'密码登录'}</td><td><span className={'admin-status '+(u.disabled?'disabled':'')}>{u.disabled?'已停用':'正常'}</span></td><td>{u.createdAt?new Date(u.createdAt).toLocaleString('zh-CN'):'—'}</td><td>{u.lastLogin?new Date(u.lastLogin).toLocaleString('zh-CN'):'—'}</td><td><div className="admin-row-actions"><button disabled={busy} onClick={async()=>{const name=prompt('修改昵称',u.name);if(name!==null&&await act({action:'user',id:u.id,name},'昵称已更新'))await load()}}>编辑</button><button disabled={busy} onClick={async()=>{if(confirm((u.disabled?'启用':'停用')+'用户 '+u.username+'？')&&await act({action:'user',id:u.id,disabled:!u.disabled},'用户状态已更新'))await load()}}>{u.disabled?'启用':'停用'}</button>{!u.sso&&<button disabled={busy} onClick={async()=>{const password=prompt('输入新密码（10–128 位）。现有会话将失效。');if(password&&await act({action:'user',id:u.id,password},'密码已重置'))await load()}}>重置密码</button>}</div></td></tr>)}</tbody></table>{!visible.length&&<p>没有符合条件的用户</p>}</div><div className="admin-pagination"><span>已加载 {users.length} 位用户</span><button disabled={cursor==='0'||busy} onClick={()=>void load(cursor)}>{cursor==='0'?'已加载全部':'加载更多用户'}</button></div></section><aside><section className="admin-card"><h2><ShieldCheck/>安全配置</h2><p>管理员凭据通过部署环境变量管理。</p><dl><dt>管理路径</dt><dd>/{path}</dd><dt>管理员密码</dt><dd>仅从 PASSWORD 环境变量读取</dd><dt>会话期限</dt><dd>2 小时，修改凭据后失效</dd></dl><button className="admin-primary" onClick={()=>setTab('settings')}>管理 Turnstile 与 SSO</button></section><section className="admin-card"><h2>最近操作</h2>{logs.map((l,i)=><div className="admin-log" key={i}><b>{l.action}</b><small>{new Date(l.time).toLocaleString('zh-CN')}</small></div>)}</section></aside></div>}
 {tab==='settings'&&config&&<div className="admin-settings-grid"><section className="admin-card"><h2><Bell/>网站公告</h2><label className="admin-switch"><input type="checkbox" checked={config.announcement.enabled} onChange={e=>update('announcement','enabled',e.target.checked)}/>显示公告</label><label>公告内容<textarea rows={5} maxLength={2000} value={config.announcement.text} onChange={e=>update('announcement','text',e.target.value)}/></label><p>公告以纯文本显示在音乐网站顶部。</p></section><section className="admin-card"><h2><ShieldCheck/>Cloudflare Turnstile</h2><label>Site Key<input value={config.turnstile.siteKey} onChange={e=>update('turnstile','siteKey',e.target.value)} placeholder="留空使用环境变量"/></label><label>Secret Key<input type="password" autoComplete="new-password" value={config.turnstile.secretKey||''} onChange={e=>update('turnstile','secretKey',e.target.value)} placeholder={config.turnstile.secretConfigured?'已配置，留空保留':'填写密钥或使用环境变量'}/></label><p>账号密码登录和注册强制验证。后台值优先于环境变量。允许域名在 Cloudflare Turnstile 控制台设置。</p><a href="https://dash.cloudflare.com/?to=/:account/turnstile" target="_blank" rel="noreferrer">打开 Cloudflare 控制台 ↗</a></section>{Object.entries(names).map(([id,label])=>{const p=config.sso[id];return <section className="admin-card" key={id}><h2><KeyRound/>{label} SSO</h2><label className="admin-switch"><input type="checkbox" disabled={id==='nodeseek'} checked={p.enabled} onChange={e=>provider(id,'enabled',e.target.checked)}/>启用登录</label>{id==='nodeseek'?<p>等待提供 NodeSeek 官方 SSO 接入文档后启用；尚未确认授权接口，不会展示不可用的登录按钮。</p>:<><label>Client ID<input value={p.clientId} onChange={e=>provider(id,'clientId',e.target.value)}/></label><label>Client Secret<input type="password" autoComplete="new-password" value={p.clientSecret||''} placeholder={p.secretConfigured?'已配置，留空保留':'填写应用密钥'} onChange={e=>provider(id,'clientSecret',e.target.value)}/></label><label>回调地址<input readOnly value={base+'/api/sso/'+id+'/callback'} onFocus={e=>e.target.select()}/></label><p>请在平台创建 OAuth 应用并填写以上精确回调地址。首次 SSO 登录同样需要邀请码。</p></>}</section>})}<div className="admin-save"><button className="admin-primary" disabled={busy} onClick={save}>{busy?'正在保存…':'保存所有配置'}</button><button disabled={busy} onClick={()=>void load()}>重新读取</button></div></div>}
 {tab==='data'&&<section className="admin-card admin-data"><h2><Settings/>音乐数据备份与恢复</h2><p>导出用户的歌单、收藏、播放和搜索记录。不包含密码、会话、SSO 身份绑定或站点密钥；不是完整账号迁移备份。</p><p>导入按用户名恢复到已有账号，会覆盖其现有音乐记录。单次最多 1000 个用户、5 MB 文件。</p><button className="admin-primary" disabled={busy} onClick={async()=>{const j=await act({action:'export'},'音乐数据已导出');if(j){const url=URL.createObjectURL(new Blob([JSON.stringify(j,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='resonance-music-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}}><Download size={16}/>导出音乐数据</button><label className="admin-import"><Upload size={17}/>选择备份文件<input type="file" accept="application/json,.json" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>5000000){setError('文件不得超过 5 MB');return}try{const data=JSON.parse(await file.text());if(confirm('将按用户名覆盖备份中用户的现有歌单、收藏及历史记录。请先导出备份，确认恢复？'))await act({action:'import',data,confirm:'RESTORE'},'音乐记录恢复完成')}catch{setError('无法读取 JSON 备份')}}}/></label></section>}
 </main></div>
}
