'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Headphones,ChevronRight,RefreshCw,Music2} from 'lucide-react';
import {sceneCategories,moodCategories,genreCategories,type CuratedFeed,type CuratedPlaylist} from './curated-types';
import type {Mix,Song} from './music-types';
import {Artwork} from './artwork';
const count=(n:number)=>n>=10000?(n/10000).toFixed(1)+'万':String(n);
function Picture({url}:{url:string}){return url?<img src={url} alt="" loading="lazy" onError={e=>{e.currentTarget.style.visibility='hidden'}}/>:<Music2 className="curated-placeholder"/>}
export function CuratedPage({onOpen,recent,play}:{onOpen:(mix:Mix)=>void;recent:Song[];play:(s:Song,list:Song[])=>void}){
 const [feed,setFeed]=useState<CuratedFeed|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[opening,setOpening]=useState(''),[rotation,setRotation]=useState(0),[expanded,setExpanded]=useState('');const controller=useRef<AbortController|null>(null);
 async function load(signal?:AbortSignal){setBusy(true);setError('');try{const r=await fetch('/api/curated',{signal});const j=await r.json() as CuratedFeed&{error?:string};if(!r.ok)throw Error(j.error);setFeed(j)}catch(e){if(!signal?.aborted)setError((e as Error).message)}finally{if(!signal?.aborted)setBusy(false)}}
 useEffect(()=>{const c=new AbortController();void load(c.signal);return()=>{c.abort();controller.current?.abort()}},[]);
 async function open(p:CuratedPlaylist){controller.current?.abort();const c=new AbortController();controller.current=c;setOpening(p.id);setError('');try{const r=await fetch('/api/curated?id='+p.id,{signal:c.signal});const j=await r.json() as Mix&{error?:string};if(!r.ok||!j.songs?.length)throw Error(j.error||'这个歌单暂时没有可播放曲目');if(!c.signal.aborted)onOpen(j)}catch(e){if(!c.signal.aborted)setError((e as Error).message)}finally{if(!c.signal.aborted)setOpening('')}}
 const pick=(cat:string)=>{const rows=feed?.groups[cat]||[];return rows.length?rows[rotation%rows.length]:undefined};
 const tile=(cat:string,style='scene')=>{const p=pick(cat);return <button key={cat} className={`curated-tile ${style}`} disabled={!p||!!opening} onClick={()=>p&&void open(p)}>{p&&<Picture url={p.cover}/>}<span className="curated-tile-copy"><b>{cat==='地铁'?'通勤必听':cat==='浪漫'?'恋爱':cat}</b><small>{p?.title||'暂未获取到歌单'}</small>{p&&<em><Headphones size={12}/>{count(p.plays)}</em>}</span></button>};
 const heading=(title:string,subtitle:string,id:string)=><div className="curated-heading"><h2>{title}</h2><p>{subtitle}</p><button onClick={()=>setExpanded(expanded===id?'':id)}>{expanded===id?'收起':'查看更多'}<ChevronRight size={15}/></button></div>;
 if(!feed)return <div className="empty-state"><p>{busy?'正在加载网络精选歌单…':error||'暂未获取到歌单'}</p>{!busy&&<button onClick={()=>void load()}>重新加载</button>}</div>;
 return <section className="curated-page">{error&&<p className="curated-message" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></p>}{opening&&<p className="curated-message" role="status">正在读取完整歌单…</p>}{feed.stale&&<p className="secondary">网络暂不可用，正在显示上次更新的歌单。</p>}<div className="curated-heroes">{['旅行','夜晚','华语'].map((cat,i)=>{const p=pick(cat);return <button key={cat} className="curated-hero" disabled={!p||!!opening} onClick={()=>p&&void open(p)}>{p&&<Picture url={p.cover}/>}<span><small>{['本期推荐','深夜电台','华语精选'][i]}</small><h2>{p?.title||cat}</h2><em>{['用音乐陪伴每一段旅程','让音乐陪你度过每一个夜晚','那些触动心灵的旋律'][i]}</em><b><Play size={14} fill="currentColor"/>打开歌单</b></span></button>})}</div><section>{heading('场景歌单','在不同的场景，遇见不一样的音乐','scene')}<div className="curated-scenes">{sceneCategories.map(c=>tile(c))}</div></section><div className="curated-middle"><section>{heading('情绪歌单','总有一首歌，懂你的情绪','mood')}<div className="curated-moods">{moodCategories.map(c=>tile(c,'mood'))}</div></section><section>{heading('风格 / 流派','探索更广阔的音乐世界','genre')}<div className="curated-genres">{genreCategories.map(c=>tile(c,'genre'))}</div></section></div>{expanded&&<section className="curated-expanded"><div className="curated-heading"><h2>更多歌单</h2></div><div className="curated-more-grid">{(expanded==='scene'?sceneCategories:expanded==='mood'?moodCategories:genreCategories).flatMap(c=>(feed.groups[c]||[]).slice(1,3)).map((p,i)=><button key={p.id+':'+i} disabled={!!opening} onClick={()=>void open(p)}><Picture url={p.cover}/><b>{p.title}</b><small>{p.count} 首歌曲</small></button>)}</div></section>}<div className="curated-bottom"><section><div className="curated-heading"><h2>今日为你推荐</h2><button onClick={()=>setRotation(v=>v+1)}><RefreshCw size={13}/>换一批</button></div><div className="curated-recommended">{['流行','华语','放松','治愈'].map(c=>tile(c==='流行'?'轻音乐':c,'recommend'))}</div></section><section><div className="curated-heading"><h2>最近常听</h2><p>继续喜欢的旋律</p></div><div className="curated-recent">{recent.slice(0,3).map((s,i)=><button key={s.id} onClick={()=>play(s,recent)}><span>{i+1}</span><Artwork song={s}/><b>{s.title}<small>{s.artist}</small></b><Play size={16}/></button>)}{!recent.length&&<p className="secondary">开始聆听后，你喜欢的音乐会出现在这里。</p>}</div></section><section><div className="curated-heading"><h2>近期更新</h2></div><div className="curated-newest">{feed.newest.slice(0,4).map(p=><button key={p.id} disabled={!!opening} onClick={()=>void open(p)}><Picture url={p.cover}/><b>{p.title}</b><small>{p.count} 首歌曲</small></button>)}</div></section></div><p className="curated-attribution">歌单与封面来自网易云音乐公开歌单 · {new Date(feed.updated).toLocaleDateString('zh-CN')} 更新</p></section>
}

