'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,Pause,Heart,History,ListMusic,Disc3,Shuffle,ChevronRight,Cloud,Moon,Sun,Leaf} from 'lucide-react';
import {Artwork} from './artwork';
import type {Feed,Mix,Song} from './music-types';
import type {CuratedFeed,CuratedPlaylist} from './curated-types';
const categories:Record<string,string[]>={'随心精选':['治愈','夜晚','咖啡馆','电子','民谣','旅行'],'心情场景':['快乐','伤感','放松','学习','工作','浪漫'],'曲风流派':['华语','摇滚','电子','爵士','说唱','轻音乐']};
export function HomePage({feed,recent,favoriteCount,playlistCount,current,playing,go,play,recommend,toggle,onOpen,reload,feedError}:{feed:Feed|null;recent:Song[];favoriteCount:number;playlistCount:number;current:Song|null;playing:boolean;go:(view:string)=>void;play:(song:Song,list:Song[])=>void;recommend:()=>void;toggle:()=>void;onOpen:(mix:Mix)=>void;reload:()=>void;feedError:string}){
 const [catalog,setCatalog]=useState<CuratedFeed|null>(null),[error,setError]=useState(''),[category,setCategory]=useState('随心精选'),[rotation,setRotation]=useState(0),[opening,setOpening]=useState(''),[now,setNow]=useState<Date|null>(null),[retry,setRetry]=useState(0);const request=useRef<AbortController|null>(null);
 useEffect(()=>{setNow(new Date());const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const c=new AbortController();setError('');fetch('/api/curated',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('推荐歌单暂时未能加载');setCatalog(await r.json())}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[retry]);
 useEffect(()=>()=>request.current?.abort(),[]);
 const pick=(cat:string)=>{const rows=catalog?.groups[cat]||[];return rows[rotation%Math.max(1,rows.length)]};
 async function open(p:CuratedPlaylist){request.current?.abort();const c=new AbortController();request.current=c;setOpening(p.id);setError('');try{const r=await fetch('/api/curated?id='+p.id,{signal:c.signal});const j=await r.json() as Mix & {error?:string};if(!r.ok||!j.songs?.length)throw Error(j.error||'歌单暂时无法读取');if(!c.signal.aborted)onOpen(j)}catch(e){if(!c.signal.aborted)setError((e as Error).message)}finally{if(!c.signal.aborted)setOpening('')}}
 const hot=feed?.mixes.find(m=>m.id==='3778678')?.songs||feed?.mixes[0]?.songs||[];
 const fresh=feed?.mixes.find(m=>m.id==='3779629')?.songs||[];
 const hero=pick('夜晚')||pick('旅行');const hour=now?.getHours()??12;const greeting=hour<6?'夜深了':hour<12?'上午好':hour<18?'下午好':'晚上好';
 return <div className="home-dashboard"><div className="home-primary"><section className="home-welcome">{hero&&<img className="home-hero-image" src={hero.cover} alt=""/>}<div className="home-welcome-copy"><p>{now?now.toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'}):'音乐与你 / RESONANCE'}</p><h2>{greeting}，<br/>今天也有好音乐相伴</h2><span>在旋律里，遇见更好的自己。</span><div className="home-hero-actions"><button className="home-primary-action" disabled={!current&&!feed} onClick={()=>current?toggle():recommend()}>{current&&playing?<Pause size={18}/>:<Play size={18} fill="currentColor"/>}{current?(playing?'暂停播放':'继续播放'):'播放推荐'}</button><button disabled={!feed} onClick={recommend}><Shuffle size={17}/>每日推荐</button></div></div><button className="home-daily-card" disabled={!hero||!!opening} onClick={()=>hero&&void open(hero)}><span className="home-disc"><Disc3 size={44}/></span><span><b>今日歌单</b><small>{hero?.title||'正在寻找好音乐…'}</small></span><ChevronRight size={18}/></button></section>
 <div className="home-shortcuts">{[{label:'我喜欢的音乐',sub:favoriteCount+' 首歌曲',icon:Heart,view:'favorites'},{label:'最近播放',sub:recent.length+' 首歌曲',icon:History,view:'recent'},{label:'精选歌单',sub:'发现更多音乐灵感',icon:Disc3,view:'mixes'},{label:'我的歌单',sub:playlistCount+' 个歌单',icon:ListMusic,view:'library'}].map(({label,sub,icon:Icon,view},i)=><button key={view} onClick={()=>go(view)}><span className={'home-shortcut-icon shortcut-'+i}><Icon size={23}/></span><span><b>{label}</b><small>{sub}</small></span></button>)}</div>
 {(error||feedError)&&<div className="home-notice" role="status">{error||feedError}<button onClick={()=>{setRetry(v=>v+1);reload()}}>重新加载</button></div>}{opening&&<p className="home-notice" role="status">正在打开歌单…</p>}
 <section className="home-recommendations"><div className="home-section-heading"><h2>为你推荐</h2><div className="home-tabs">{Object.keys(categories).map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><button className="home-more" onClick={()=>setRotation(v=>v+1)}><Shuffle size={14}/>换一批</button></div><div className="home-playlist-grid">{categories[category].map(cat=>{const p=pick(cat);return <button className="home-playlist-card" key={cat} disabled={!p||!!opening} onClick={()=>p&&void open(p)}><div className="home-playlist-art">{p&&<img loading="lazy" src={p.cover} alt=""/>}<span className="home-card-tag">{cat}</span><span className="home-card-play"><Play size={16} fill="currentColor"/></span></div><b>{p?.title||'正在加载…'}</b><small>{p?p.count+' 首歌曲 · '+(p.plays>=10000?(p.plays/10000).toFixed(1)+'万':p.plays)+' 次播放':'精选网络歌单'}</small></button>})}</div></section>
 <section><div className="home-section-heading"><h2>新歌上榜</h2><span>从新歌榜发现新鲜旋律</span><button className="home-more" disabled={!fresh.length} onClick={()=>{const m=feed?.mixes.find(m=>m.id==='3779629');if(m)onOpen(m)}}>更多<ChevronRight size={14}/></button></div><div className="home-new-songs">{fresh.slice(0,8).map(s=><button key={s.id} onClick={()=>play(s,fresh)}><Artwork song={s}/><b>{s.title}</b><small>{s.artist}</small></button>)}</div>{!fresh.length&&<p className="secondary">{feed?'新歌榜暂未获取到，请稍后重试。':'正在读取网络新歌榜…'}</p>}</section><p className="home-attribution">歌单、榜单及封面来自网易云音乐公开数据{feed?' · '+new Date(feed.updated).toLocaleDateString('zh-CN')+' 更新':''}{feed?.stale||catalog?.stale?' · 当前显示最近一次加载的内容':''}</p></div>
 <aside className="home-right"><div className="home-note" style={hero?{backgroundImage:`linear-gradient(120deg,rgba(16,30,38,.85),rgba(25,42,52,.65)),url("${hero.cover}")`}:undefined}><span>“</span><p>给生活留一段旋律，<br/>也给自己片刻放松。</p><small>YOUR DAILY MUSIC MOMENT</small></div><section className="home-hot"><div className="home-section-heading"><h2>热门歌曲</h2><button className="home-more" disabled={!hot.length} onClick={()=>{const m=feed?.mixes.find(m=>m.id==='3778678')||feed?.mixes[0];if(m)onOpen(m)}}>更多<ChevronRight size={14}/></button></div>{hot.slice(0,5).map((s,i)=><button className="home-hot-song" key={s.id} onClick={()=>play(s,hot)}><span>{i+1}</span><Artwork song={s}/><span><b>{s.title}</b><small>{s.artist}</small></span><Play size={14}/></button>)}{!hot.length&&<p className="secondary">正在加载热门歌曲…</p>}</section><section className="home-moods"><div className="home-section-heading"><h2>心情电台</h2></div><div>{[{cat:'放松',en:'RELAX',icon:Cloud},{cat:'学习',en:'FOCUS',icon:Leaf},{cat:'快乐',en:'HAPPY',icon:Sun},{cat:'伤感',en:'SAD',icon:Moon}].map(({cat,en,icon:Icon},i)=>{const p=pick(cat);return <button key={cat} className={'mood-'+i} disabled={!p||!!opening} onClick={()=>p&&void open(p)}><Icon size={23}/><span>{cat==='学习'?'专注':cat}<small>{en}</small></span></button>})}</div></section></aside></div>
}

