'use client';
import {useState,useRef,useEffect} from 'react';
import {Search,Play,ArrowUpRight,Music2} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export type OnlineItem={id:string;provider:string;title:string;artist:string;album:string;cover:string;duration:string};
export type OnlineQuality={id:string;label:string;detail:string;url:string;mime?:string};
export function OnlineMusic({onPlay,onCancel}:{onPlay:(item:OnlineItem,qualities:OnlineQuality[])=>void;onCancel:()=>void}){
const [provider,setProvider]=useState('at38'),[query,setQuery]=useState(''),[items,setItems]=useState<OnlineItem[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(''),[error,setError]=useState(''),[searched,setSearched]=useState(false),[page,setPage]=useState(1),[hasMore,setHasMore]=useState(false);
const searchAbort=useRef<AbortController|null>(null),playAbort=useRef<AbortController|null>(null),lastQuery=useRef('');
useEffect(()=>()=>{searchAbort.current?.abort();playAbort.current?.abort()},[]);
function changeSource(value:string){searchAbort.current?.abort();playAbort.current?.abort();setProvider(value);setItems([]);setSearched(false);setError('');setBusy(false);setLoading('');setPage(1);setHasMore(false)}
async function search(next=1){const q=(next===1?query:lastQuery.current).trim();if(!q)return;searchAbort.current?.abort();playAbort.current?.abort();setLoading('');const controller=new AbortController();searchAbort.current=controller;setBusy(true);setError('');setItems([]);setSearched(true);try{const r=await fetch('/api/music?'+new URLSearchParams({provider,q,page:String(next)}),{signal:controller.signal});const j=await r.json() as {error?:string;items:OnlineItem[];hasMore:boolean};if(!r.ok)throw Error(j.error);setItems(j.items);setHasMore(j.hasMore);setPage(next);lastQuery.current=q}catch(e){if(!controller.signal.aborted)setError((e as Error).message)}finally{if(!controller.signal.aborted)setBusy(false)}}
async function play(item:OnlineItem){playAbort.current?.abort();const controller=new AbortController();playAbort.current=controller;setLoading(item.id);setError('');onCancel();try{const r=await fetch('/api/music?'+new URLSearchParams({action:'play',provider:item.provider,id:item.id,q:lastQuery.current}),{signal:controller.signal});const j=await r.json() as {error?:string;qualities:OnlineQuality[]};if(!r.ok)throw Error(j.error);if(!controller.signal.aborted)onPlay(item,j.qualities)}catch(e){if(!controller.signal.aborted)setError((e as Error).message)}finally{if(!controller.signal.aborted)setLoading('')}}
return <section className="online-music"><form className="online-search" onSubmit={e=>{e.preventDefault();search()}}><Select value={provider} onValueChange={v=>{if(v)changeSource(v)}} items={[{value:'at38',label:'51 音乐'},{value:'netease',label:'CoCo · 网易云'},{value:'qq',label:'CoCo · QQ 音乐'}]}><SelectTrigger aria-label="选择音乐源"><SelectValue/></SelectTrigger><SelectContent alignItemWithTrigger={false}><SelectItem value="at38">51 音乐</SelectItem><SelectItem value="netease">CoCo · 网易云</SelectItem><SelectItem value="qq">CoCo · QQ 音乐</SelectItem></SelectContent></Select><label><Search size={20}/><input aria-label="在线搜索歌名或艺人" placeholder="搜索歌名或艺人" maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/></label><button className="red-btn" disabled={busy||!query.trim()}>{busy?'搜索中…':'搜索'}</button></form><div className="source-note"><span>在线音乐由所选音乐源提供，曲目与音质以实际返回为准。</span><a href="https://cocodownloader.markqq.com/" target="_blank" rel="noreferrer">CoCo 原站<ArrowUpRight size={14}/></a><a href="https://www.at38.cn/" target="_blank" rel="noreferrer">51 音乐 · 原站访问<ArrowUpRight size={14}/></a></div>{error&&<p className="source-error" role="alert">{error}</p>}<p className="source-status" role="status">{busy?'正在查找歌曲…':loading?'正在获取可用音质…':searched&&!error?(items.length?items.length+' 首歌曲 · 第 '+page+' 页':'没有找到歌曲，试试其他关键词或音乐源。'):'输入歌名或艺人，探索更多音乐。'}</p><div className="online-results">{items.map(item=><article key={item.provider+item.id}><div className="online-cover">{item.cover?<img src={item.cover} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<Music2/>}</div><div className="online-title"><b>{item.title}</b><span>{item.artist} · {item.album}</span></div><span className="online-duration">{item.duration}</span><button aria-label={'播放 '+item.title} disabled={loading===item.id} onClick={()=>play(item)}>{loading===item.id?'加载中':<Play size={18}/>}</button></article>)}</div>{searched&&!busy&&!error&&<div className="source-pagination"><button disabled={page===1} onClick={()=>search(page-1)}>上一页</button><span>第 {page} 页</span><button disabled={!hasMore||page>=20} onClick={()=>search(page+1)}>下一页</button></div>}</section>}
