'use client';
import {useEffect,useRef,useState} from 'react';
import {Settings,Maximize2,Minimize2,Music2,House,Search,Disc3,Play,Pause,SkipBack,SkipForward,Volume2,Heart,History,AudioLines,Shuffle,Repeat2,ChevronRight,ArrowLeft,ListMusic,Menu,X,Headphones,LoaderCircle} from 'lucide-react';
import {useAccount,AccountDialog,AccountContext,AddToPlaylist,PersonalPlaylists} from './account';
import {SiteAnnouncement} from './site-features';
import {SearchPage} from './search-page';
import {HomePage} from './home-page';
import {CuratedPage} from './curated-page';
import {SettingsPage} from './settings-page';
import {Artwork} from './artwork';
import {RecordArtwork} from './record-artwork';
import {resolvePlayback,forgetPlayback,completeDuration} from './playback-cache';
import {nextIndex,type PlayMode} from './playback-order';
import {LyricsPanel} from './lyrics-panel';
import type {Song,Quality,Mix,Feed} from './music-types';
const fmt=(seconds:number)=>`${Math.floor((seconds||0)/60)}:${String(Math.floor((seconds||0)%60)).padStart(2,'0')}`;
const key=(s:Song)=>`${s.provider}:${s.id}`;
const shuffled=<T,>(list:T[])=>{const out=[...list];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
const unique=(songs:Song[])=>songs.filter((s,i,a)=>a.findIndex(t=>`${t.title.toLowerCase()}|${t.artist.toLowerCase()}`===`${s.title.toLowerCase()}|${s.artist.toLowerCase()}`)===i);
function Cover({mix,index=0}:{mix:Mix;index?:number}){if(mix.cover)return <img className="mix-network-cover" src={mix.cover} alt={mix.title}/>;return <div className={`mix-cover tone-${mix.tone}`}><span className="cover-orbit"/><span className="cover-wave"/><small>{['ON REPEAT','SOFT FEELINGS','GOOD ENERGY','AFTER HOURS'][index%4]}</small><strong>{mix.title}</strong><span className="cover-caption">RESONANCE / DAILY SELECTION</span></div>}
function SongRow({song,list,current,favorites,unavailable,playing,loadingSong,playSong,like,toggle}:{song:Song;list:Song[];current:Song|null;favorites:Song[];unavailable:Record<string,string>;playing:boolean;loadingSong:string;playSong:(song:Song,list?:Song[])=>void;like:(song:Song)=>void;toggle:()=>void}){const isCurrent=current&&key(current)===key(song);const saved=favorites.some(x=>key(x)===key(song));const reason=unavailable[key(song)];return <article className={`music-row ${isCurrent?'is-current':''}`}><button className="song-main" disabled={!!reason} title={reason} onClick={()=>playSong(song,list)} aria-label={`播放 ${song.title}`}><Artwork song={song}/><span><b>{song.title}</b><small>{song.artist}{reason&&<em className="unavailable-label"> · 暂不可播放</em>}</small></span></button><button className={`icon-btn favorite ${saved?'is-liked':''}`} onClick={()=>like(song)} aria-label={`${saved?'取消喜欢':'喜欢'} ${song.title}`} aria-pressed={saved}><Heart size={18} fill={saved?'currentColor':'none'}/></button><AddToPlaylist song={song}/><span className="row-time">{song.duration|| (song.durationMs?fmt(song.durationMs/1000):'—')}</span><button className="icon-btn row-play" disabled={!!reason} title={reason} onClick={()=>isCurrent?toggle():playSong(song,list)} aria-label={`${isCurrent&&playing?'暂停':'播放'} ${song.title}`}>{loadingSong===key(song)?<LoaderCircle className="spin" size={17}/>:isCurrent&&playing?<Pause size={17}/>:<Play size={17}/>}</button></article>}
export default function Home(){
 const [immersive,setImmersive]=useState(false);
 const [recordEnabled,setRecordEnabled]=useState(false),[recordSpeed,setRecordSpeed]=useState(1);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('resonance-record-effect')||'null');if(p){setRecordEnabled(p.enabled===true);if([.5,1,1.5,2].includes(p.speed))setRecordSpeed(p.speed)}}catch{}},[]);
 function changeRecord(enabled:boolean,speed:number){setRecordEnabled(enabled);setRecordSpeed(speed);try{localStorage.setItem('resonance-record-effect',JSON.stringify({enabled,speed}))}catch{}}
 async function leaveFullscreen(){setImmersive(false);if(document.fullscreenElement)try{await document.exitFullscreen()}catch{}}
 async function enterFullscreen(){setView('player');setMobile(false);setImmersive(true);window.scrollTo({top:0});try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen()}catch{/* Keep the viewport-filling layout on browsers without native fullscreen. */}}
 useEffect(()=>{const change=()=>{if(!document.fullscreenElement)setImmersive(false)};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setImmersive(false)};document.addEventListener('fullscreenchange',change);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('fullscreenchange',change);document.removeEventListener('keydown',escape)}},[]);
 useEffect(()=>{if(!immersive)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[immersive]);
 const [collapsed,setCollapsed]=useState(false);
 useEffect(()=>{try{setCollapsed(localStorage.getItem('resonance-sidebar-collapsed')==='true')}catch{}},[]);
 function toggleSidebar(){if(window.matchMedia('(max-width:767px)').matches){setMobile(v=>!v);return}setCollapsed(v=>{try{localStorage.setItem('resonance-sidebar-collapsed',String(!v))}catch{}return !v})}
 const [view,setView]=useState('home'),[mobile,setMobile]=useState(false),[feed,setFeed]=useState<Feed|null>(null),[mixes,setMixes]=useState<Mix[]>([]),[suggested,setSuggested]=useState<Song[]>([]),[feedBusy,setFeedBusy]=useState(true),[feedError,setFeedError]=useState('');
 const [selectedMix,setSelectedMix]=useState<Mix|null>(null),[query,setQuery]=useState(''),[results,setResults]=useState<Song[]>([]),[searchBusy,setSearchBusy]=useState(false),[searchDone,setSearchDone]=useState(false),[searchError,setSearchError]=useState(''),[hasMore,setHasMore]=useState(false),[page,setPage]=useState(1);
 const account=useAccount();const {favorites,recent}=account.library;const recorded=useRef('');const recoveries=useRef(0),stallTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 const [current,setCurrent]=useState<Song|null>(null),[queue,setQueue]=useState<Song[]>([]),[qualities,setQualities]=useState<Quality[]>([]),[quality,setQuality]=useState(''),[playing,setPlaying]=useState(false),[loadingSong,setLoadingSong]=useState(''),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[volume,setVolume]=useState(.65),[playMode,setPlayMode]=useState<PlayMode>('sequence'),[unavailable,setUnavailable]=useState<Record<string,string>>({}),[error,setError]=useState(''),[lyrics,setLyrics]=useState<{time:number;end?:number;text:string}[]>([]),[lyricText,setLyricText]=useState(''),[lyricBusy,setLyricBusy]=useState(false);
 const audio=useRef<HTMLAudioElement>(null),resolver=useRef<AbortController|null>(null),searchAbort=useRef<AbortController|null>(null),lastQuery=useRef(''),wantsPlay=useRef(false),pendingSeek=useRef(0),currentRef=useRef<Song|null>(null),attempted=useRef<Song|null>(null);
 const active=qualities.find(q=>q.id===quality)||qualities[0];const selectedSongs=view==='favorites'?favorites:view==='recent'?recent:view==='queue'?queue:selectedMix?.songs||[];
 function go(next:string){if(immersive)void leaveFullscreen();setView(next);setMobile(false);window.scrollTo({top:0,behavior:'smooth'})}
 function randomize(data:Feed,target='all'){if(target!=='songs')setMixes(shuffled(data.mixes).slice(0,4).map(m=>({...m,songs:shuffled(m.songs)})));if(target!=='mixes')setSuggested(shuffled(unique(data.mixes.flatMap(m=>m.songs))).slice(0,6));}
 async function loadFeed(signal?:AbortSignal){setFeedBusy(true);setFeedError('');try{const r=await fetch('/api/discover',{signal});const j=await r.json() as Feed&{error?:string};if(!r.ok||!j.mixes?.length)throw Error(j.error||'推荐暂时未能加载');setFeed(j);randomize(j)}catch(e){if(!signal?.aborted)setFeedError('推荐暂时未能加载，请稍后重试。你仍可以搜索喜欢的歌曲。')}finally{if(!signal?.aborted)setFeedBusy(false)}}
 useEffect(()=>{const c=new AbortController();loadFeed(c.signal);return()=>c.abort()},[]);
 useEffect(()=>()=>{resolver.current?.abort();searchAbort.current?.abort()},[]);
 useEffect(()=>{if(audio.current)audio.current.volume=volume},[volume,active?.url]);
 useEffect(()=>{if(!current||!playing||playMode!=='sequence'||queue.length<2)return;const index=queue.findIndex(s=>key(s)===key(current));if(index<0)return;const next=queue[(index+1)%queue.length];if(unavailable[key(next)])return;let cancelled=false;let warm:HTMLAudioElement|undefined;const timer=setTimeout(()=>{resolvePlayback(next).then(j=>{if(cancelled||!j.ok||!j.qualities?.[0])return;warm=new Audio();warm.preload='metadata';warm.src=j.qualities[0].url;warm.load()}).catch(()=>{})},400);return()=>{cancelled=true;clearTimeout(timer);if(warm){warm.removeAttribute('src');warm.load()} }},[current,playing,queue,playMode,unavailable]);
 useEffect(()=>{setLyrics([]);setLyricText('');setLyricBusy(false);if(!current)return;const c=new AbortController();setLyricBusy(true);const params=new URLSearchParams({id:current.id,title:current.title,artist:current.artist,album:current.album||'',duration:String((current.durationMs||0)/1000)});fetch('/api/lyrics?'+params,{signal:c.signal}).then(r=>r.json()).then(j=>{const data=j as {lines?:{time:number;end?:number;text:string}[];text?:string};if(!c.signal.aborted){setLyrics(data.lines||[]);setLyricText(data.text||'')}}).catch(()=>{}).finally(()=>{if(!c.signal.aborted)setLyricBusy(false)});return()=>c.abort()},[current?.id,current?.title,current?.artist,current?.album,current?.durationMs]);
 const durationIds=results.filter(s=>!s.durationMs&&!s.duration&&/^(wy_\d+|qq_[a-zA-Z0-9]+)$/.test(s.id)).map(s=>s.id).join(',');
 useEffect(()=>{if(!durationIds)return;const c=new AbortController();fetch('/api/durations?'+new URLSearchParams({ids:durationIds}),{signal:c.signal}).then(r=>r.json()).then((j:any)=>{if(c.signal.aborted)return;setResults(items=>items.map(s=>j.durations?.[s.id]?{...s,durationMs:j.durations[s.id],duration:fmt(j.durations[s.id]/1000)}:s))}).catch(()=>{});return()=>c.abort()},[durationIds]);
 function like(song:Song){account.like(song)}
 async function search(next=1,term?:string){const q=(term??(next===1?query:lastQuery.current)).trim();if(!q||!account.ready)return;if(next===1){setQuery(q);account.searchHistory('search-save',q);}searchAbort.current?.abort();const c=new AbortController();searchAbort.current=c;setSearchBusy(true);setSearchError('');setSearchDone(true);setResults([]);try{const r=await fetch('/api/music?'+new URLSearchParams({provider:'at38',q,page:String(next)}),{signal:c.signal});const j=await r.json() as {items:Song[];hasMore:boolean;error?:string};if(!r.ok)throw Error(j.error);if(c.signal.aborted)return;setResults(unique(j.items).map(s=>({...s,keyword:q})));setHasMore(j.hasMore);setPage(next);lastQuery.current=q}catch(e){if(!c.signal.aborted)setSearchError('搜索暂时不可用，请稍后再试。')}finally{if(!c.signal.aborted)setSearchBusy(false)}}
 async function playSong(song:Song,list?:Song[],resume=0,recovering=false){if(song.importStatus==='unmatched'){setError('未找到歌曲资源：'+song.title+' · '+song.artist);return}if(!recovering)recoveries.current=0;clearTimeout(stallTimer.current);attempted.current=song;if(unavailable[key(song)]){setError(unavailable[key(song)]);return}resolver.current?.abort();const c=new AbortController();resolver.current=c;setLoadingSong(key(song));setError('');if(list)setQueue(list);try{const j=await resolvePlayback(song);if(!j.ok||!j.qualities?.length){if(c.signal.aborted)return;if(['AUDIO_UNAVAILABLE','AUDIO_NOT_FOUND','AUDIO_ACCESS_DENIED','PREVIEW_ONLY'].includes(j.code||''))setUnavailable(items=>({...items,[key(song)]:j.error||'暂不可播放'}));throw Error(j.code?j.error||'这首歌暂时无法播放，换一首试试。':'歌曲服务暂时无法响应，请稍后重试。');}if(c.signal.aborted)return;const available=j.qualities.filter(x=>!/(?:\/preview\/|preview=1)/i.test(x.url));if(!available.length)throw Error('这首歌暂时无法播放，换一首试试。');audio.current?.pause();setPlaying(false);const verifiedSong={...song,durationMs:(j.expectedDuration||0)*1000||song.durationMs};currentRef.current=verifiedSong;setCurrent(verifiedSong);setQualities(available);setQuality(available[0].id);setTime(resume);setDuration(0);pendingSeek.current=resume;wantsPlay.current=true;if(!recovering)recorded.current='';if(active?.url===available[0].url)audio.current?.load()}catch(e){if(!c.signal.aborted)setError((e as Error).message)}finally{if(!c.signal.aborted)setLoadingSong('')}}
 function recoverPlayback(){clearTimeout(stallTimer.current);if(!current||loadingSong||!wantsPlay.current)return;setPlaying(false);if(recoveries.current>=3){wantsPlay.current=false;setError('暂时没有可用音频，请稍后重试。');return}recoveries.current++;forgetPlayback(current,active?.url);playSong(current,undefined,audio.current?.currentTime||time,true)}
 useEffect(()=>()=>clearTimeout(stallTimer.current),[]);
 async function startAudio(){const target=audio.current;try{await target?.play()}catch(e){if(target!==audio.current)return;if((e as Error).name!=='AbortError'){wantsPlay.current=false;setError('播放未能开始，请再次点击播放。')}}}
 function loaded(){const a=audio.current;if(!a)return;const total=Number.isFinite(a.duration)?a.duration:0;const expected=(currentRef.current?.durationMs||0)/1000;if(total>0&&!completeDuration(total,expected)){a.pause();recoverPlayback();return}setDuration(total);if(pendingSeek.current){a.currentTime=Math.min(pendingSeek.current,Math.max(0,total-.1));pendingSeek.current=0}if(wantsPlay.current)startAudio()}
 function toggle(){if(loadingSong){resolver.current?.abort();setLoadingSong('');return}if(playing){wantsPlay.current=false;audio.current?.pause()}else if(current){wantsPlay.current=true;if(error){forgetPlayback(attempted.current||current);playSong(attempted.current||current);}else startAudio()}else if(suggested[0])playSong(suggested[0],suggested)}
 function playRecommendations(){if(!feed)return;const pool=unique(feed.mixes.flatMap(m=>m.songs)).filter(s=>!unavailable[key(s)]);const next=shuffled(pool);if(next.length>1&&current&&key(next[0])===key(current))[next[0],next[1]]=[next[1],next[0]];if(next.length)playSong(next[0],next)}
 function skip(step:number,automatic=false){if(!queue.length)return;const selected=loadingSong?attempted.current:current;const index=selected?queue.findIndex(s=>key(s)===key(selected)):-1;const next=nextIndex(queue.length,index,playMode,step,automatic);if(next<0){wantsPlay.current=false;setPlaying(false);return}playSong(queue[next]);}
 function changeQuality(id:string){if(id===quality)return;pendingSeek.current=audio.current?.currentTime||0;wantsPlay.current=playing;audio.current?.pause();setQuality(id)}
 function seek(value:number){if(audio.current&&duration){audio.current.currentTime=value;setTime(value)}}
 const title=({settings:'设置',library:'我的歌单',home:'发现音乐',search:'搜索音乐',mixes:'精选歌单',favorites:'喜欢的音乐',recent:'最近播放',player:'正在播放',queue:'待播列表',mix:selectedMix?.title||'歌单'} as Record<string,string>)[view];
 return <AccountContext.Provider value={song=>{if(account.user)account.setAdding(song);else account.setOpen(true)}}><div className={`music-app ${collapsed?'sidebar-collapsed':''} ${immersive?'immersive-player':''}${collapsed?'sidebar-collapsed':''}`}><AccountDialog account={account}/>{account.error&&!account.open&&<div className="account-notice" role="alert">{account.error}<button onClick={()=>account.setError('')}>关闭</button></div>}<button className={`nav-scrim ${mobile?'shown':''}`} aria-label="关闭导航" onClick={()=>setMobile(false)}/><aside id="music-sidebar" className={`music-sidebar ${mobile?'open':''}`}><a className="music-brand" href="#" onClick={e=>{e.preventDefault();go('home')}}><span><Music2/></span><b>共鸣</b></a><small className="brand-en">RESONANCE</small><p className="nav-label">音乐</p><nav aria-label="主导航">{[{id:'home',label:'发现音乐',icon:House},{id:'search',label:'搜索音乐',icon:Search},{id:'mixes',label:'精选歌单',icon:Disc3},{id:'player',label:'正在播放',icon:AudioLines}].map(({id,label,icon:Icon})=><button key={id} className={view===id?'active':''} onClick={()=>go(id)} aria-current={view===id?'page':undefined}><Icon size={19}/>{label}{id==='player'&&playing&&<span className="nav-dot"/>}</button>)}</nav><p className="nav-label my-label">我的音乐</p><nav aria-label="我的音乐"><button className={view==='library'?'active':''} onClick={()=>go('library')}><ListMusic size={19}/>我的歌单</button><button className={view==='favorites'?'active':''} onClick={()=>go('favorites')}><Heart size={19}/>喜欢的音乐</button><button className={view==='recent'?'active':''} onClick={()=>go('recent')}><History size={19}/>最近播放</button></nav><div className="sidebar-bottom"><button className="settings-entry" onClick={()=>go('settings')} aria-current={view==='settings'?'page':undefined}><Settings size={19}/>设置</button><p>让音乐，陪你一会儿。</p></div></aside>
 <main className={`music-main ${view==='player'?'player-main':''}`}><div className="music-topbar">{immersive&&<button className="icon-btn fullscreen-back" onClick={leaveFullscreen} aria-label="退出全屏"><ArrowLeft/></button>}<button className="icon-btn menu-toggle" aria-label="展开或收起侧栏" aria-controls="music-sidebar" onClick={toggleSidebar}><Menu/></button><div><h1>{title}</h1><p>{view==='home'?'今天的好歌，总有一首与你同频。':view==='search'?'想听的旋律，在这里找到。':'让喜欢的音乐，一直陪着你。'}</p></div><button className="global-search" onClick={()=>go('search')}><Search size={17}/><span>搜索歌曲、艺人、歌单</span></button>{view==='player'&&<button className="fullscreen-button" onClick={()=>immersive?leaveFullscreen():enterFullscreen()} aria-label={immersive?'退出全屏':'全屏播放'}>{immersive?<Minimize2 size={18}/>:<Maximize2 size={18}/>}<span>{immersive?'退出全屏':'全屏播放'}</span></button>}<button className="music-avatar" aria-label="账号" onClick={()=>account.setOpen(true)}>{account.user?.name.slice(0,1)||'登录'}</button></div>
 <SiteAnnouncement/>
 {view==='library'&&<PersonalPlaylists account={account} play={(s,list)=>{setPlayMode('sequence');void playSong(s,list)}} shuffle={list=>{const next=shuffled(list);setPlayMode('shuffle');void playSong(next[0],next)}} current={current} playing={playing} toggle={toggle}/>} 
 {view==='home'&&<HomePage feed={feed} recent={recent} favoriteCount={favorites.length} playlistCount={account.library.playlists.length} current={current} playing={playing} go={go} play={playSong} recommend={playRecommendations} toggle={toggle} onOpen={mix=>{setSelectedMix(mix);go('mix')}} reload={()=>loadFeed()} feedError={feedError}/>}
 {view==='search'&&<SearchPage query={query} setQuery={setQuery} search={term=>void search(1,term)} busy={searchBusy} ready={account.ready} done={searchDone} reset={()=>{searchAbort.current?.abort();setSearchBusy(false);setSearchDone(false);setSearchError('')}} history={account.library.searches} removeHistory={q=>account.searchHistory('search-remove',q)} clearHistory={()=>account.searchHistory('search-clear')} feed={feed} onOpen={mix=>{setSelectedMix(mix);go('mix')}} play={playSong}>{searchBusy?<div className="loading-text" role="status"><LoaderCircle className="spin"/>正在查找歌曲…</div>:searchError?<div className="inline-error" role="alert">{searchError}<button onClick={()=>void search()}>重试</button></div>:<><div className="music-section-title"><h2>歌曲</h2><span>{results.length} 首结果</span></div>{results.length?<div className="single-song-list">{results.map(song=><SongRow key={key(song)} song={song} list={results} current={current} favorites={favorites} unavailable={unavailable} playing={playing} loadingSong={loadingSong} playSong={playSong} like={like} toggle={toggle}/>)}</div>:<div className="empty-state"><Search/><p>没有找到相关歌曲，试试其他歌名或艺人。</p></div>}{(page>1||hasMore)&&<div className="pagination"><button disabled={page<=1} onClick={()=>void search(page-1)}>上一页</button><span>{page}</span><button disabled={!hasMore||page>=20} onClick={()=>void search(page+1)}>下一页</button></div>}</>}</SearchPage>}
 {view==='mixes'&&<CuratedPage onOpen={mix=>{setSelectedMix(mix);go('mix')}} recent={recent} play={playSong}/>} 
 {['mix','favorites','recent','queue'].includes(view)&&<section>{view==='mix'&&selectedMix&&<div className="mix-detail"><Cover mix={selectedMix}/><div><p className="eyebrow">DAILY SELECTION</p><h2>{selectedMix.title}</h2><p>{selectedMix.description} · {selectedMix.songs.length} 首歌曲</p><button className="primary-btn" onClick={()=>playSong(selectedMix.songs[0],selectedMix.songs)}><Play size={17}/>播放歌单</button></div></div>}{selectedSongs.length?<div className="single-song-list">{selectedSongs.map(song=><SongRow current={current} favorites={favorites} unavailable={unavailable} playing={playing} loadingSong={loadingSong} playSong={playSong} like={like} toggle={toggle} key={key(song)} song={song} list={selectedSongs}/>)}</div>:<div className="empty-state"><Music2/><p>{view==='favorites'?'点击歌曲旁的爱心，把喜欢的旋律收在这里。':view==='recent'?'开始聆听后，你的足迹会出现在这里。':'挑一首喜欢的歌，开始今天的音乐。'}</p><button onClick={()=>go('home')}>去发现音乐</button></div>}</section>}
 <SettingsPage visible={view==='settings'}/>{view==='player'&&(current?<><section className="listening-page"><div className="listening-art"><RecordArtwork song={current} enabled={recordEnabled} playing={playing} speed={recordSpeed}/><h2>{current.title}</h2><p>{current.artist} · {current.album}</p><div className="record-settings"><button type="button" role="switch" aria-checked={recordEnabled} onClick={()=>changeRecord(!recordEnabled,recordSpeed)}><Disc3 size={16}/><span>唱片旋转</span><span className="record-switch"/></button><label>转速<select aria-label="唱片旋转速度" value={recordSpeed} disabled={!recordEnabled} onChange={e=>changeRecord(recordEnabled,Number(e.target.value))}><option value="0.5">慢速</option><option value="1">标准</option><option value="1.5">较快</option><option value="2">快速</option></select></label></div></div><LyricsPanel lines={lyrics} text={lyricText} busy={lyricBusy} time={time} onSeek={seek}/></section></>:<div className="empty-state"><Headphones/><p>挑一首喜欢的歌，开始聆听。</p><button onClick={()=>go('home')}>去发现音乐</button></div>)}
 </main><div className="floating-player"><button className="current-info" onClick={()=>go('player')}><Artwork song={current||undefined}/><span><b>{current?.title||'挑一首喜欢的歌'}</b><small>{current?.artist||'今天，听点不一样的'}</small></span></button><button className={`icon-btn player-like ${current&&favorites.some(s=>key(s)===key(current))?'is-liked':''}`} disabled={!current} onClick={()=>current&&like(current)} aria-label="喜欢当前歌曲"><Heart size={19} fill={current&&favorites.some(s=>key(s)===key(current))?'currentColor':'none'}/></button><div className="player-transport"><button className="icon-btn playback-mode" aria-label={`播放模式：${{sequence:'顺序播放',repeat:'单曲循环',shuffle:'随机播放'}[playMode]}，点击切换`} title={{sequence:'顺序播放',repeat:'单曲循环',shuffle:'随机播放'}[playMode]} onClick={()=>setPlayMode(m=>m==='sequence'?'repeat':m==='repeat'?'shuffle':'sequence')}>{playMode==='shuffle'?<Shuffle size={20}/>:playMode==='repeat'?<Repeat2 size={20}/>:<ListMusic size={20}/>}</button><button className="icon-btn previous-track" disabled={!queue.length} aria-label="上一首" onClick={()=>skip(-1)}><SkipBack size={23} fill="currentColor"/></button><button className="round-play" aria-label={playing?'暂停':'播放'} onClick={toggle} disabled={!current&&!suggested.length}>{loadingSong?<LoaderCircle className="spin" size={22}/>:playing?<Pause size={22} fill="currentColor"/>:<Play size={22} fill="currentColor"/>}</button><button className="icon-btn" disabled={!queue.length} aria-label="下一首" onClick={()=>skip(1)}><SkipForward size={23} fill="currentColor"/></button></div><div className="player-seek"><span>{fmt(time)}</span><input type="range" aria-label="播放进度" min="0" max={duration||1} step=".1" value={Math.min(time,duration||1)} disabled={!duration} onChange={e=>seek(Number(e.target.value))}/><span>{fmt(duration)}</span></div><div className="quality-dropdown"><select aria-label="音质" disabled={!qualities.length} value={active?.id||''} onChange={e=>changeQuality(e.target.value)}>{!qualities.length&&<option value="">音质</option>}{qualities.map(q=><option key={q.id} value={q.id}>{q.mime==='audio/flac'?'无损 FLAC':q.mime==='audio/wav'?'无损 WAV':q.mime==='audio/mpeg'?'MP3':q.label}</option>)}</select></div><div className="player-volume"><Volume2 size={18}/><input type="range" min="0" max="1" step=".01" value={volume} onChange={e=>setVolume(Number(e.target.value))} aria-label="音量"/></div>{!immersive&&<button className="icon-btn player-fullscreen" aria-label={immersive?'退出全屏':'全屏播放'} onClick={()=>immersive?leaveFullscreen():enterFullscreen()}>{immersive?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button>}<button className="lyrics-button" onClick={()=>go('player')}>歌词</button><button className="icon-btn player-queue" onClick={()=>go('queue')} aria-label="待播列表"><ListMusic size={21}/></button></div>
 {error&&<div className="player-toast" role="alert"><span>{error}</span><button onClick={()=>{if(attempted.current){forgetPlayback(attempted.current);playSong(attempted.current)}}} disabled={!attempted.current||!!unavailable[key(attempted.current)]}>重试</button><button aria-label="关闭提示" onClick={()=>setError('')}><X size={16}/></button></div>}<audio key={active?.url||'idle'} ref={audio} preload="metadata" onLoadedMetadata={loaded} onPlay={()=>{setPlaying(true);setError('');if(current&&recorded.current!==key(current)){recorded.current=key(current);account.record(current)}}} onPause={()=>{clearTimeout(stallTimer.current);setPlaying(false)}} onTimeUpdate={()=>setTime(audio.current?.currentTime||0)} onWaiting={()=>{clearTimeout(stallTimer.current);if(wantsPlay.current)stallTimer.current=setTimeout(recoverPlayback,12000)}} onPlaying={()=>clearTimeout(stallTimer.current)} onError={e=>{if(e.currentTarget===audio.current&&!loadingSong)recoverPlayback()}} onEnded={()=>{if(loadingSong)return;if(playMode==='repeat'){if(audio.current)audio.current.currentTime=0;startAudio()}else skip(1,true)}}>{active&&<source src={active.url} type={active.mime}/>}</audio></div></AccountContext.Provider>
}







