'use client';
import {useEffect,useRef,useState} from 'react';
import {parseTrackFile,type ExternalPlaylist} from './playlist-import/model';
import type {Song} from './music-types';
export function PlaylistImport({owner,onSave}:{owner:string;onSave:(data:Record<string,unknown>)=>Promise<void>}){
 const [open,setOpen]=useState(false),[url,setUrl]=useState(''),[list,setList]=useState<ExternalPlaylist|null>(null),[songs,setSongs]=useState<Song[]>([]),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false);const run=useRef(0),abort=useRef<AbortController|null>(null);
 useEffect(()=>()=>{run.current++;abort.current?.abort()},[owner]);
 async function request(body:unknown,signal:AbortSignal){const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});const j:any=await r.json();if(!r.ok)throw Error(j.error||'导入失败，请稍后重试');return j}
 function cancel(){run.current++;abort.current?.abort();setBusy(false);setProgress('已取消，可以重新导入')}
 async function prepare(file?:File){const task=++run.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setBusy(true);setError('');setList(null);setSongs([]);setConfirmed(false);try{setProgress('正在读取歌单…');if(file&&file.size>500000)throw Error('文件不能超过 500KB');const data:ExternalPlaylist=file?{name:file.name.replace(/\.(csv|json)$/i,''),source:'文件导入',tracks:parseTrackFile(await file.text())}:await request({action:'import-read',url},controller.signal);if(task!==run.current)return;setList(data);const output:Song[]=[];for(let i=0;i<data.tracks.length;i+=3){setProgress(`正在匹配 ${Math.min(i+3,data.tracks.length)} / ${data.tracks.length} 首`);const j=await request({action:'import-match',tracks:data.tracks.slice(i,i+3)},controller.signal);if(task!==run.current)return;output.push(...j.items);setSongs([...output])}setProgress('匹配完成，请核对后保存')}catch(e){if(task===run.current)setError((e as Error).message)}finally{if(task===run.current)setBusy(false)}}
 async function save(){if(!list||busy)return;setBusy(true);setProgress('正在保存…');setError('');try{await onSave({action:'import-save',name:list.name,source:list.source,songs});setOpen(false);setList(null);setSongs([])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="playlist-import"><button className="primary-btn" onClick={()=>setOpen(v=>!v)}>导入外部歌单</button>{open&&<section className="import-panel"><h3>导入外部歌单</h3><p>网易云 · QQ 音乐 · 酷狗 · YouTube Music · Spotify</p><form onSubmit={e=>{e.preventDefault();void prepare()}}><input aria-label="外部歌单链接" placeholder="粘贴公开歌单的完整链接" value={url} maxLength={2000} onChange={e=>setUrl(e.target.value)}/><button disabled={busy||!url.trim()} className="primary-btn">读取并匹配</button></form><label className="import-file">或导入 CSV / JSON 文件<input type="file" accept=".csv,.json,text/csv,application/json" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void prepare(f);e.target.value=''}}/></label><p>文件包含 title（歌曲名称）与 artist（歌手），每次最多 500 首。短分享链接请先在原平台打开，复制完整歌单地址。</p>{busy&&progress!=='正在保存…'&&<button onClick={cancel}>取消匹配</button>}<p role="status">{progress}</p>{error&&<p role="alert">{error}</p>}{list&&<><label>歌单名称<input value={list.name} maxLength={60} onChange={e=>setList({...list,name:e.target.value})}/></label>{list.warning&&<label className="import-warning"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{list.warning} 我已核对并接受本次导入范围。</label>}<p>读取 {list.tracks.length} 首 · 已匹配 {songs.filter(s=>s.importStatus==='matched').length} 首 · 未匹配 {songs.filter(s=>s.importStatus==='unmatched').length} 首</p><div className="import-preview">{songs.map((s,i)=><div key={i} className={s.importStatus==='unmatched'?'unmatched-song':''}><b>{s.title}</b><span>{s.artist}</span><small>{s.importStatus==='unmatched'?'未找到歌曲资源':'已匹配'}</small></div>)}</div><button className="primary-btn" disabled={busy||songs.length!==list.tracks.length||!songs.length||!!list.warning&&!confirmed} onClick={save}>保存到我的歌单</button></>}</section>}</div>
}


