'use client';
import './search-page.css';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Search,ArrowRight,History,X,Play,Disc3,LayoutGrid,AudioLines,Flame,RefreshCw,ChevronRight} from 'lucide-react';
import {Artwork} from './artwork';
import type {Feed,Mix,Song} from './music-types';
import type {CuratedFeed,CuratedPlaylist} from './curated-types';
export function SearchPage({query,setQuery,search,busy,ready,done,reset,history,removeHistory,clearHistory,feed,onOpen,play,children}:{query:string;setQuery:(q:string)=>void;search:(q?:string)=>void;busy:boolean;ready:boolean;done:boolean;reset:()=>void;history:string[];removeHistory:(q:string)=>void;clearHistory:()=>void;feed:Feed|null;onOpen:(mix:Mix)=>void;play:(s:Song,list:Song[])=>void;children:ReactNode}){
 const [catalog,setCatalog]=useState<CuratedFeed|null>(null),[error,setError]=useState(''),[rotation,setRotation]=useState(0),[opening,setOpening]=useState(false),[retry,setRetry]=useState(0);const request=useRef<AbortController|null>(null);
 useEffect(()=>{const c=new AbortController();setError('');fetch('/api/curated',{signal:c.signal}).then(async r=>{if(!r.ok)throw Error('推荐歌单暂时未能加载');setCatalog(await r.json() as CuratedFeed)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>{c.abort();request.current?.abort()}},[retry]);
 const pick=(cat:string)=>{const rows=catalog?.groups[cat]||[];return rows[rotation%Math.max(1,rows.length)]};
 async function open(p:CuratedPlaylist){request.current?.abort();const c=new AbortController();request.current=c;setOpening(true);setError('');try{const r=await fetch('/api/curated?id='+p.id,{signal:c.signal});const j=await r.json() as Mix&{error?:string};if(!r.ok||!j.songs?.length)throw Error(j.error||'歌单暂时无法读取');if(!c.signal.aborted)onOpen(j)}catch(e){if(!c.signal.aborted)setError((e as Error).message)}finally{if(!c.signal.aborted)setOpening(false)}}
 const songs=feed?.mixes.find(m=>m.id==='3778678')?.songs||feed?.mixes[0]?.songs||[];
 const terms=[...new Set(songs.map(s=>s.title))];const suggestions=terms.slice(rotation%Math.max(1,terms.length-10),rotation%Math.max(1,terms.length-10)+10);
 const heading=(Icon:typeof Search,title:string,sub:string,action?:()=>void)=><div className="search-section-title"><Icon size={20}/><h2>{title}</h2>{sub&&<small>{sub}</small>}{action&&<button onClick={action}>换一批<RefreshCw size={13}/></button>}</div>;
 return <section className="search-page search-discovery"><div className="search-hero"><div className="search-intro"><h2>在这里，<br/>遇见你喜欢的音乐</h2><p>探索旋律，发现心动。<br/>总有一首歌与你同频。</p></div><div className="search-center"><form className="unified-search" role="search" onSubmit={e=>{e.preventDefault();search()}}><Search size={25}/><input aria-label="搜索歌曲或歌手" placeholder="搜索歌曲、歌手，发现喜欢的音乐" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="search-clear" type="button" aria-label="清空搜索内容" onClick={()=>setQuery('')}><X size={17}/></button>}<button className="search-submit" type="submit" aria-label="搜索" disabled={busy||!query.trim()||!ready}><ArrowRight size={23}/></button></form><div className="search-suggestions"><span>试试搜索</span>{['周杰伦','Taylor Swift','五月天','陈奕迅',...songs.slice(0,4).map(s=>s.title)].map((q,i)=><button key={q+i} onClick={()=>search(q)} disabled={!ready}>{q}</button>)}</div></div><p className="search-motto">音乐让平凡的日子<br/>也闪闪发光 ✧</p></div>
 <div className="search-dashboard"><div className="search-main-column"><section className="search-panel search-recent">{heading(History,'最近搜索','')}<button className="search-history-clear" disabled={!history.length||!ready} onClick={clearHistory}>清空</button>{history.length?<div className="history-chips">{history.map(q=><span className="history-chip" key={q}><button disabled={!ready} onClick={()=>search(q)}><History size={15}/>{q}</button><button disabled={!ready} aria-label={'删除搜索记录 '+q} onClick={()=>removeHistory(q)}><X size={12}/></button></span>)}</div>:<p className="search-muted">搜索过的音乐会出现在这里。</p>}</section>
 {done?<section className="search-panel search-results-panel"><div className="search-section-title"><Search size={20}/><h2>搜索结果</h2><button onClick={reset}>返回探索<ChevronRight size={14}/></button></div>{children}</section>:<><section className="search-panel">{heading(Disc3,'推荐歌单','让好音乐发现更多可能',()=>setRotation(n=>n+1))}{error&&<p className="search-muted" role="status">{error}<button onClick={()=>setRetry(n=>n+1)}>重新加载</button></p>}{opening&&<p className="search-muted" role="status">正在读取歌单…</p>}<div className="search-playlist-grid">{['夜晚','学习','旅行','治愈','咖啡馆','怀旧'].map(cat=>{const p=pick(cat);return <button key={cat} disabled={!p||opening} onClick={()=>p&&void open(p)}><div className="search-tile-art">{p&&<img src={p.cover} alt="" loading="lazy"/>}<span className="search-tile-category">{cat}</span><span className="search-tile-play"><Play size={15} fill="currentColor"/></span></div><b>{p?.title||'正在加载歌单…'}</b><small>{p?p.count+' 首歌曲':'网络精选'}</small></button>})}</div></section>
 <section className="search-panel">{heading(LayoutGrid,'音乐风格','探索不同风格，发现更多精彩')}<div className="search-genre-grid">{['华语','摇滚','民谣','电子','爵士','说唱','怀旧','影视原声','轻音乐'].map(cat=>{const p=pick(cat);return <button key={cat} disabled={!p||opening} onClick={()=>p&&void open(p)}>{p&&<img src={p.cover} alt="" loading="lazy"/>}<b>{cat}</b></button>})}</div></section><section className="search-panel">{heading(AudioLines,'大家都在听','此刻，从热歌榜遇见好音乐')}<div className="search-listening">{songs.slice(0,5).map(s=><button key={s.id} onClick={()=>play(s,songs)}><Artwork song={s}/><span><b>{s.title}</b><small>{s.artist}</small></span><Play size={16}/></button>)}</div>{!songs.length&&<p className="search-muted">榜单正在加载，请稍候。</p>}</section></>}
 </div><aside className="search-side-column"><section className="search-panel">{heading(Flame,'热门歌曲搜索','',()=>setRotation(n=>n+3))}<div className="search-trending">{suggestions.map((q,i)=><button key={q} onClick={()=>search(q)} disabled={!ready}><span>{i+1}</span><b>{q}</b><ArrowRight size={12}/></button>)}</div>{!suggestions.length&&<p className="search-muted">正在读取热歌榜…</p>}</section><section className="search-panel">{heading(Disc3,'热门榜单','')}<div className="search-chart-grid">{feed?.mixes.map((mix,i)=><article className={'search-chart chart-'+i} key={mix.id}><button className="search-chart-heading" onClick={()=>onOpen(mix)}><Disc3 size={20}/><b>{mix.title}</b><ChevronRight size={15}/></button><div>{mix.songs.slice(0,5).map((s,n)=><button key={s.id} onClick={()=>play(s,mix.songs)}><span>{n+1}</span><b>{s.title}</b></button>)}</div><button className="search-chart-play" aria-label={'播放'+mix.title} disabled={!mix.songs.length} onClick={()=>play(mix.songs[0],mix.songs)}><Play size={13} fill="currentColor"/>播放榜单</button></article>)}</div>{!feed&&<p className="search-muted">正在读取网络榜单…</p>}</section></aside></div><p className="search-data-note">歌单及榜单来自网易云音乐公开数据 · 热门搜索词取自热歌榜歌曲名称</p></section>
}

