import {PlaybackError} from './playback-error';
import {searchAt38,playAt38} from './at38';
const ORIGIN='https://cocodownloader.markqq.com';
const providers=new Set(['netease','qq','at38']);
function safeUrl(value:unknown){if(typeof value!=='string')return '';try{const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port||u.hostname==='localhost'||u.hostname.endsWith('.local')||/^[\d.]+$/.test(u.hostname)||u.hostname.includes(':'))return '';return u.href}catch{return ''}}
async function upstream(path:string){const r=await fetch(ORIGIN+path,{signal:AbortSignal.timeout(18000),headers:{Accept:'application/json'},redirect:'manual'});if(!r.ok)throw Error('音乐源暂时无法响应，请稍后重试或切换音乐源。');const text=await r.text();if(text.length>1000000)throw Error('音乐源返回内容过大。');return JSON.parse(text)}
const response=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(request:Request){const p=new URL(request.url).searchParams,provider=p.get('provider')||'',action=p.get('action')||'search';if(!providers.has(provider))return response({error:'请选择可用的音乐源。'},400);
try{if(action==='search'){const q=(p.get('q')||'').trim(),page=Number(p.get('page')||1);if(!q||q.length>100||!Number.isInteger(page)||page<1||page>20)return response({error:'请输入 1–100 个字的关键词。'},400);if(provider==='at38')return response(await searchAt38(q,page));const j=await upstream('/api/search?'+new URLSearchParams({q,provider,limit:'20',offset:String((page-1)*20)}));if(!Array.isArray(j.items))throw Error('音乐源返回异常，请切换音乐源。');const items=j.items.slice(0,20).filter((x:any)=>x&&/^[a-zA-Z0-9_-]{1,100}$/.test(String(x.id))).map((x:any)=>({id:String(x.id),provider,title:String(x.title||'未命名歌曲').slice(0,200),artist:String(x.artist||'未知艺人').slice(0,200),album:String(x.album||'单曲').slice(0,200),cover:safeUrl(typeof x.cover==='string'?x.cover.replace(/^http:/,'https:'):''),duration:String(x.duration||'').slice(0,10)}));return response({items,hasMore:items.length===20});}
if(action!=='play')return response({error:'不支持的操作。'},400);const id=p.get('id')||'';if(!/^[a-zA-Z0-9_-]{1,100}$/.test(id))return response({error:'歌曲信息无效。'},400);
if(provider==='at38')return response(await playAt38(id,p.get('q')||''));
const levels=provider==='netease'?['standard','lossless']:['default'];const results=await Promise.allSettled(levels.map(async level=>{const params=new URLSearchParams({id,provider});if(provider==='netease')params.set('extra',JSON.stringify({selectedLevel:level}));const info=await upstream('/api/url?'+params);const url=safeUrl(info.url);if(!url)throw Error('未返回可播放链接');const raw=String(info.type||'').toLowerCase();const type=['mp3','m4a','aac','flac','wav','ogg'].includes(raw)?raw:'unknown';const lossless=type==='flac'||type==='wav';return {id:level,label:lossless?'无损':level==='standard'?'标准':'原始音质',detail:(type==='unknown'?'格式由音源提供':type.toUpperCase())+(info.bitrate?' · '+String(info.bitrate).slice(0,30):''),url,mime:({mp3:'audio/mpeg',m4a:'audio/mp4',aac:'audio/aac',flac:'audio/flac',wav:'audio/wav',ogg:'audio/ogg'} as Record<string,string>)[type]};}));
const qualities=results.flatMap(r=>r.status==='fulfilled'?[r.value]:[]).filter((q,i,list)=>list.findIndex(x=>x.url===q.url)===i);if(!qualities.length)return response({error:'此歌曲暂未返回可播放音源，请切换音乐源或前往原站。'},502);return response({qualities});
}catch(e){if(e instanceof PlaybackError)return response({error:e.message,code:e.code},e.status);console.warn('Music source failure', (e as Error).name,(e as Error).message);return response({error:(e as Error).name==='TimeoutError'?'音乐源响应超时，请重试或切换音乐源。':'音乐源暂时不可用，请稍后重试或切换音乐源。'},502);}}
