import {scryptSync,randomBytes} from 'node:crypto';
import {ApiError,PREFIX,SETTINGS,adminIdentity,audit,body,database,digest,limit,nonce,origin,publicSettings,readCookie,requireAdmin,result,same,secureCookie,settings,userKeys,type DB} from './core';
export const dynamic='force-dynamic';
export async function GET(r:Request){return handle(r)}
export async function POST(r:Request){return handle(r)}
async function handle(r:Request){let db:DB|undefined;try{const admin=adminIdentity();if(!admin||r.headers.get('x-admin-path')!==admin.path)throw new ApiError('页面不存在',404);if(r.method==='POST')origin(r);db=await database();const b=r.method==='POST'?await body(r,5000000):{};
 if(b.action==='login'){await limit(db,r,'admin-login');if(!same(String(b.username||''),admin.name)||!same(String(b.password||''),admin.password))throw new ApiError('账号或密码不正确',401);const token=nonce();await db.set(PREFIX+'admin-session:'+digest(token),admin.version,{EX:7200});await audit(db,'管理员登录');return result({ok:true},200,{'Set-Cookie':secureCookie(r,'resonance_admin',token,7200)})}
 await requireAdmin(r,db);
 if(r.method==='GET'){const url=new URL(r.url),cursor=url.searchParams.get('cursor')||'0';if(!/^\d{1,20}$/.test(cursor))throw new ApiError('游标无效');const [next,keys]=await userKeys(db,cursor);const users=[];for(const key of keys){const u=JSON.parse(await db.get(key)||'null');if(u)users.push({id:key.slice((PREFIX+'user:').length),username:u.username,name:u.name,disabled:!!u.disabled,createdAt:u.createdAt||null,lastLogin:u.lastLogin||null,sso:!!u.sso})}const logs=await db.eval("return redis.call('LRANGE',KEYS[1],0,19)",{keys:[PREFIX+'admin-audit'],arguments:[]}) as string[];return result({users,cursor:next,settings:publicSettings(await settings(db)),logs:logs.map((s:string)=>JSON.parse(s))})}
 if(b.action==='logout'){await db.del(PREFIX+'admin-session:'+digest(readCookie(r,'resonance_admin')));return result({ok:true},200,{'Set-Cookie':secureCookie(r,'resonance_admin','',0)})}
 if(b.action==='settings'){const old=await settings(db),s=b.settings;if(!s||typeof s!=='object')throw new ApiError('配置无效');const next={...old,announcement:{enabled:!!s.announcement?.enabled,text:String(s.announcement?.text||'').slice(0,2000)},turnstile:{siteKey:String(s.turnstile?.siteKey||'').trim().slice(0,200),secretKey:String(s.turnstile?.secretKey||old.turnstile.secretKey).trim().slice(0,300)},sso:{...old.sso}};for(const id of ['nodeseek','linuxdo','github','google']){const p=s.sso?.[id]||{},prev=old.sso[id];if(id==='nodeseek'&&p.enabled)throw new ApiError('NodeSeek SSO documentation is required before enabling');next.sso[id]={enabled:!!p.enabled,clientId:String(p.clientId||'').trim().slice(0,300),clientSecret:String(p.clientSecret||prev?.clientSecret||'').trim().slice(0,1000),issuer:String(p.issuer||'').trim().slice(0,200)};if(next.sso[id].enabled&&(!next.sso[id].clientId||!next.sso[id].clientSecret))throw new ApiError(id+' 需要填写 Client ID 和 Secret');}await db.set(SETTINGS,JSON.stringify(next));await audit(db,'更新公告与登录安全配置');return result({ok:true,settings:publicSettings(next)})}
 if(b.action==='user'){if(!/^[a-f0-9]{32}$/.test(b.id))throw new ApiError('用户无效');const key=PREFIX+'user:'+b.id,raw=await db.get(key);if(!raw)throw new ApiError('用户不存在',404);const u=JSON.parse(raw);if(typeof b.disabled==='boolean')u.disabled=b.disabled;if(typeof b.name==='string')u.name=b.name.trim().slice(0,40)||u.username;if(b.password){if(u.sso)throw new ApiError('第三方账号请在原平台修改密码');if(typeof b.password!=='string'||b.password.length<10||b.password.length>128)throw new ApiError('密码须为 10–128 位');u.salt=randomBytes(16).toString('hex');u.password=scryptSync(b.password,u.salt,64).toString('hex');}const ok=await db.eval("if redis.call('GET',KEYS[1])~=ARGV[1] then return 0 end redis.call('SET',KEYS[1],ARGV[2]);return 1",{keys:[key],arguments:[raw,JSON.stringify(u)]});if(!ok)throw new ApiError('用户刚刚被修改，请刷新重试',409);if(b.password||b.disabled)await db.set(PREFIX+'revoke:'+b.id,String(Date.now()));await audit(db,'更新用户 '+u.username);return result({ok:true})}
 if(b.action==='export'){let cursor='0';const users=[];do{const [next,keys]=await userKeys(db,cursor);cursor=next;for(const key of keys){const u=JSON.parse(await db.get(key)||'null');if(u)users.push({username:u.username,library:JSON.parse(await db.get(PREFIX+'library:'+key.slice((PREFIX+'user:').length))||'{"favorites":[],"recent":[],"playlists":[],"searches":[]}')});if(users.length>1000)throw new ApiError('导出超过 1000 个用户，请分批备份');}}while(cursor!=='0');await audit(db,'导出用户音乐数据');return result({format:'resonance-library-backup',version:1,exportedAt:Date.now(),users})}
 if(b.action==='import'){const data=b.data;if(data?.format!=='resonance-library-backup'||data.version!==1||!Array.isArray(data.users)||data.users.length>1000)throw new ApiError('备份格式无效');const plans=[];const seen=new Set();for(const row of data.users){if(typeof row.username!=='string'||seen.has(row.username))throw new ApiError('用户名重复或无效');seen.add(row.username);const uid=await db.get(PREFIX+'username:'+row.username);if(!uid)throw new ApiError('用户不存在：'+row.username+'；导入只恢复已有用户的音乐记录');const library=row.library;if(!library||!Array.isArray(library.searches)||!Array.isArray(library.favorites)||!Array.isArray(library.recent)||!Array.isArray(library.playlists)||library.searches.length>20||library.favorites.length>500||library.recent.length>200||library.playlists.length>100)throw new ApiError('音乐记录格式或数量无效');for(const p of library.playlists){if(typeof p.id!=='string'||typeof p.name!=='string'||p.name.length>60||p.id.length>100||!Array.isArray(p.songs)||p.songs.length>500)throw new ApiError('歌单格式无效')}for(const s of [...library.favorites,...library.recent,...library.playlists.flatMap((p:any)=>p.songs)])if(s?.provider!=='at38'||typeof s.id!=='string'||typeof s.title!=='string'||typeof s.artist!=='string'||s.id.length>200||s.title.length>300||s.artist.length>300||(s.album&&typeof s.album!=='string')||String(s.album||'').length>300||(s.cover&&!/^https:\/\//.test(s.cover))||String(s.cover||'').length>2000)throw new ApiError('歌曲数据无效');if(library.searches.some((s:unknown)=>typeof s!=='string'||s.length>100))throw new ApiError('搜索记录无效');plans.push({key:PREFIX+'library:'+uid,value:JSON.stringify(library)})}if(b.confirm!=='RESTORE')throw new ApiError('请确认覆盖现有音乐记录');await db.eval("for i=1,#KEYS do redis.call('SET',KEYS[i],ARGV[i]) end return #KEYS",{keys:plans.map(p=>p.key),arguments:plans.map(p=>p.value)});await audit(db,'恢复 '+plans.length+' 位用户音乐记录');return result({ok:true,count:plans.length})}
 throw new ApiError('未知操作');
 }catch(e){return result({error:e instanceof ApiError?e.message:'后台服务暂不可用'},e instanceof ApiError?e.status:503)}finally{db?.destroy()}}
